error-comment-404         : Comment not found.
error-ticket-404          : Ticket not found.
error-ticket-priority     : You don't have purchased priority support.
error-user-404            : Account not found.
error-user-activated      : Account is not activated.
error-user-confirmed      : Account is not confirmed.
error-user-credentials    : Bad credentials
error-user-email          : Email address is not registered in database.
error-privileges          : You don't have any privileges for this operation.