version: '2'
services:
  helpdesk_postgres:
    image: postgres:9.6.8-alpine
    environment:
      - POSTGRES_PASSWORD=123456

  helpdesk_web:
    build: .
    ports:
      - 8000:8000
    links:
      - helpdesk_postgres
    volumes:
      - ../:/app
    working_dir: /app
    command: sh -c "npm install; node debug.js"